language: python

python:
  - "3.5"

cache:
  pip: true
  directories:
    - node_modules

install:
  - pip install -r requirements.txt
  - nvm install stable
  - npm install

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - ./manage.py test
  - ./manage.py test bdd
  - npm run lint
