os: linux
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: python
python:
  - '3.5'
node_js: '7'
env: DISPLAY=':99.0'

cache:
  pip: true
  directories:
    - node_modules

install:
  - pip install -r requirements.txt
  - npm install

before_script:
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - git clone https://github.com/compilio/compilio-runner.git
  - ./compilio-runner/bin/deploy &

script:
  - ./manage.py test
  - ./manage.py test functional
  - npm run lint
