os: linux
dist: trusty
language: python
node_js: '7'
env: DISPLAY=':99.0'
python:
  - "3.5"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  pip: true
  directories:
    - node_modules

install:
  - pip install -r requirements.txt
  - npm install

before_script:
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - ./manage.py test
  - ./manage.py test bdd
  - npm run lint
