language: python

python:
  - "3.5"

cache:
  pip: true
  directories:
    - node_modules

install:
  - pip install -r requirements.txt
  - nvm install stable
  - npm install

script:
  - ./manage.py test
  - ./manage.py test bdd
  - npm run lint
