language: python

python:
  - "3.5"

cache:
  pip: true
  directories:
    - node_modules

install:
  - pip install -r requirements.txt
  - nvm install stable
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - ./manage.py test
  - ./manage.py test bdd
  - npm run lint
