# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submitted_date',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
