# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_auto_20170508_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='token',
            new_name='id',
        ),
    ]
