# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_auto_20170510_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='compiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.Compiler'),
        ),
    ]
