# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0007_task_compiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='server_compiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.ServerCompiler'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Compiling', 'Compiling'), ('Terminated', 'Terminated'), ('Error', 'Error')], default='Pending', max_length=10),
        ),
    ]
