# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0008_auto_20170518_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='docker_prefix_command',
            field=models.CharField(default='', max_length=128),
        ),
    ]
