# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0010_auto_20170522_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='output_files_parse_code',
            field=models.TextField(null=True),
        ),
    ]
