# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0011_compiler_output_files_parse_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='session_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPILING', 'COMPILING'), ('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], default='PENDING', max_length=10),
        ),
    ]
