# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0012_auto_20170525_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(blank=True, default='9a5f496b97e54d29', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
