# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compiler', '0013_auto_20170529_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(blank=True, default='2073caff872e496a', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
