# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compiler', '0013_auto_20170529_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owners',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
