# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 12:38
from __future__ import unicode_literals

import compilio.compiler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0014_auto_20170529_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compiler',
            name='regex',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(blank=True, default=compilio.compiler.models.generate_id, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
