# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0015_auto_20170601_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compiler',
            name='docker_prefix_command',
        ),
        migrations.AddField(
            model_name='compiler',
            name='remote_command',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='input_file',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
