# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0009_compiler_docker_prefix_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='description',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiler',
            name='icon',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiler',
            name='title',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
